### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by w296488320** [yangyiyu08/ollvm-project#3]
Stack dump:
  0.	Program arguments: D:\\AndroidStudio\\SDK\\ndk\\25.2.9519653\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++.exe --target=aarch64-none-linux-android26 --sysroot=D:/AndroidStudio/SDK/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DCORE_SO_NAME=\"libhunter.so\" -DHAVE_SECCOMP_FILTER -DZHENXI_BUILD_TYPE_NOLOG -Dhunter_EXPORTS -IF:/xxxx/app/src/main/cpp/include -IF:/xxxx/nativeLib/src/main/cpp/includes -IF:/xxxxx/nativeLib/src/main/cpp/hook/Dobby/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -std=c++20 -Wno-narrowing -Wunused-parameter -Winvalid-noreturn -fvisibility=hidden -fvisibility-inlines-hidden -s -Os -ffunction-sections -fdata-sections -fomit-frame-pointer -Wl,--gc-sections -fPIC -mllvm -fla -mllvm -split -mllvm -split_num=3 -mllvm -bcf -mllvm -bcf_prob=40 -mllvm -sub -mllvm -sub_loop=3 -mllvm -sobf -O2 -g -DNDEBUG -fPIC -flto -MD -MT CMakeFiles/hunter.dir/main.cpp.o -MF CMakeFiles\\hunter.dir\\main.cpp.o.d -o CMakeFiles/hunter.dir/main.cpp.o -c F:/Hunter/app/src/main/cpp/main.cpp
  1.	<eof> parser at end of file
  2.	Per-module optimization passes
  3.	Running pass 'Function Pass Manager' on module 'F:/xxxx/app/src/main/cpp/main.cpp'.

**Comment by buffcow** [comment]
llvm放在ndk兼容性太差，建议直接用google的ndk移植编译
[google ndk](https://android.googlesource.com/toolchain/llvm-project)

**Comment by buffcow** [comment]
珍惜大佬直接手撸一个🤓

**Comment by MIkeeJY** [comment]
珍惜大佬NB

**Comment by w296488320** [comment]
别别别 ，hunter升到c++ 20 我想着编译一份ollvm, git这个14x有问题，我正在尝试下载官方的源码，然后网上有ollvm的patch文件 ，不知道还有多少坑要踩 。
